# Generated by Django 6.0.5 on 2026-06-13 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='site',
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacystock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='medical_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_batches', to='pharmacy.medicalcenter'),
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='medical_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='pharmacy.medicalcenter'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='medical_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pharmacy.medicalcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together={('medical_center', 'medicine', 'expiration_date')},
        ),
        migrations.AlterUniqueTogether(
            name='pharmacystock',
            unique_together={('medical_center', 'medicine')},
        ),
        migrations.RemoveField(
            model_name='medicinebatch',
            name='site',
        ),
        migrations.RemoveField(
            model_name='pharmacystock',
            name='site',
        ),
    ]
