# Generated by Django 6.0.5 on 2026-06-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicalcenter_remove_stockmovement_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrance'), ('OUT', 'Exit'), ('HISTORICAL_OUT', 'Historical Exit'), ('ADJUST', 'Adjustment')], max_length=14),
        ),
    ]
