# Generated by Django 6.0.5 on 2026-06-13 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
